theme:        jekyll-theme-slate

plugins:
  - jekyll-sitemap

title:        IGME 110
description:  Introduction to Interactive Media
semesterAddDropDate: TBA
semesterWithdrawDate: TBA

profName: YOUR NAME
profOffice: TBA
profEmail: TBA
officeHours: TBA
sectionNumber: "##"
semesterCode: "#2###"
sectionStartTime: TBA
sectionEndTime: TBA
sectionClassroom: TBA
discordInvite:  TBA
classStartTime: 2pm
